version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-dev}
    networks:
      - barback-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - barback-network

volumes:
  mongo-data:

networks:
  barback-network:
